### PR TITLE
Fix printing when printing complete package

### PR DESCRIPTION
**Pull request by MZO9400**
echo -e gave an extra "-e" when printing, so switched to printf

### CODE REVIEW

**Comment by akhilnarang** [comment]
Or just make it an echo

**Comment by MZO9400** [comment]
Wouldn't echo not interpret colors?

**Comment by akhilnarang** [comment]
Try and confirm

**Comment by MZO9400** [comment]
Okay

**Comment by MZO9400** [comment]
https://github.com/MZO9400/android_build-1/commit/3a7e3846f89588b73ff53a34b23538ba3823b483 added to https://github.com/OwnROM/android_build/pull/1

**Comment by OwnDroid** [comment]
Is it ready? :P

**Comment by MZO9400** [comment]
Yes it is now. New line is made and md5sum and size are also displayed :p

**Comment by OwnDroid** [comment]
Thanks!

**Pull request merged**
